CREATE DATABASE festivalss;
show databases;
use festivalss;
CREATE TABLE festivalss(id int,name_festivals varchar(30),festival_date date,festival_day varchar(20),type_festival varchar(20),noOfsweetDishes int,noOfspicydishes int,celebratedincountry varchar(20),festivaltime time,totalno_festivals int,decoratedwith varchar(30),type_pooja varchar(30),festivalinStates varchar(30),famousdueto varchar(20),isfestival boolean,famousdishsweet varchar(20),famousdishspice varchar(30),guestsinvited boolean,newClotheswored boolean);
SELECT*FROM festivalss;
INSERT INTO festivalss VALUES(1,'diwali','2022-9-24','thursday','religious festival',10,10,'India','10:00:00',40,'diyas','lakshmi','allStates','diyas',true,'holige','chakli',true,true);
INSERT INTO festivalss VALUES(2,'dasara','2022-8-20','tuesday','religious festival',5,5,'India','10:00:00',40,'flowers','varmahalakshmi','allStates','diyas',true,'paayasa','ghujiya',true,false);
INSERT INTO festivalss VALUES(3,'ramzan','2022-5-16','friday','religious festival',15,20,'India','7:00:00',40,'flowersandLights','namaaz','allStates','fasting',true,'dryFruitSalad','biriyani',true,true);
INSERT INTO festivalss VALUES(4,'holi','2022-3-13','sunday','religious festival',5,5,'India','03:00:00',40,'colors','','allStates','colors',true,'paayasa','ghujiya',true,true);
INSERT INTO festivalss VALUES(5,'bakrid','2022-7-20','saturday','religious festival',5,5,'India','10:30:00',40,'flowersandLights','namaaz','allStates','diyas','meatDistribution',true,'holige','biriyani',true,true);
INSERT INTO festivalss VALUES(7,'GaneshChaturti','2022-4-20','tuesday','religious festival',5,5,'India','10:00:00',40,'flowers','ganesh','allStates','ganapati',true,'laddoos','bhajji',true,true);
INSERT INTO festivalss VALUES(8,'RepublicDay','2022-1-26','monday','national festival',10,15,'India','07:00:00',40,'flowers','varmahalakshmi','allStates','diyas',true,'paayasa','ghujiya',true,true);
INSERT INTO festivalss VALUES(9,'IndependenceDay','2022-8-15','thursday','national festival',5,5,'India','07:00:00',40,'flowers','varmahalakshmi','allStates','diyas',true,'paayasa','ghujiya',true,true);
INSERT INTO festivalss VALUES(10,'gandhi jayanti','2022-10-2','tuesday','national festival',5,5,'India','11:00:00',40,'flowers','varmahalakshmi','allStates','diyas',true,'paayasa','ghujiya',true,true);
INSERT INTO festivalss VALUES(11,'childrensDay','2022-11-14','friday','national festival',5,5,'India','10:00:00',40,'flowers','varmahalakshmi','allStates','diyas',true,'paayasa','ghujiya',true,true);
INSERT INTO festivalss VALUES(12,'TeachersDay','2022-9-5','monday','national festival',5,5,'India','12:00:00',40,'flowers','varmahalakshmi','allStates','diyas',true,'paayasa','ghujiya',true,true);
INSERT INTO festivalss VALUES(13,'pongal','2022-1-10','friday','cultural festival',5,5,'India','10:00:00',40,'flowers','nature','TN','agriculturalthings',true,'sakkari pongal','medu vada',true,false);
INSERT INTO festivalss VALUES(14,'navaratri','2022-8-20','saturday','cultural festival',5,5,'India','10:00:00',40,'flowers','durga','gujarat','garba',true,'paayasa','dhokla',true,true);
INSERT INTO festivalss VALUES(15,'onam','2022-8-20','tuesday','religious festival',5,5,'India','10:00:00',40,'flowers','','kerala','boat racing',true,'AdaPradhanam','puttuandKadalacurry',true,false);
INSERT INTO festivalss VALUES(15,'Kartikekadashi','2022-8-20','fullweek','culturalfestival',5,5,'India','24:00:00',40,'flowers','kartik','gujarat','flowersandLights',true,'kheer','ghujiya',true,false);
INSERT INTO festivalss VALUES(16,'naagarapanchami','2022-2-15','wednesday','religious festival',5,5,'India','10:00:00',40,'flowers','naagpooja','karnataka','flowersandLights',true,'karchikai','bhajji',true,false);
INSERT INTO festivalss VALUES(17,'buddhapoornima','2022-8-20','tuesday','religious festival',5,5,'India','10:00:00',40,'flowers','','uttarpradesh','diyas',true,'paayasa','ghujiya',true,true);
INSERT INTO festivalss VALUES(18,'mothersday','2022-3-22','monday','national festival',5,5,'India','10:00:00',40,'flowers','mother','allStates','diyas',true,'kheer','pulaav',true,true);
INSERT INTO festivalss VALUES(19,'ugadi','2022-4-12','tuesday','religious festival',5,5,'India','10:00:00',40,'flowers','banni','allStates','banni',true,'karchikai','chitranna',true,true);
INSERT INTO festivalss VALUES(20,'sankranti','2022-1-10','saturday','religious festival',5,5,'India','10:00:00',40,'flowers','bhoomitaai','allStates','yellubelladistribution',true,'sesamumladdu','chivda',true,true);
INSERT INTO festivalss VALUES(21,'janmashtami','2022-8-20','wednesday','cultural festival',5,5,'India','10:00:00',40,'flowers','krishna','allStates','dahihandi',true,'modak','momos',true,false);
INSERT INTO festivalss VALUES(22,'muharram','2022-2-20','tuesday','religious festival',5,5,'India','10:00:00',40,'flowers','ali','allStates','sharbat distribution',true,'chonge','friedrice',true,false);
INSERT INTO festivalss VALUES(23,'sankashti','2022-1-11','sunday','religious festival',5,5,'India','10:00:00',40,'flowers','moon','allStates','fast',true,'paayasa','ghujiya',true,false);
INSERT INTO festivalss VALUES(24,'goodfriday','2022-8-20','friday','national festival',5,5,'India','10:00:00',40,'flowers','jesus','allStates','prayer',true,'paayasa','ghujiya',true,true);
INSERT INTO festivalss VALUES(25,'ramnavami','2022-8-20','tuesday','national festival',5,5,'India','10:00:00',40,'flowers','varmahalakshmi','allStates','diyas',true,'paayasa','ghujiya',true,true);
INSERT INTO festivalss VALUES(26,'hajj','2022-8-20','tuesday','national festival',5,5,'India','10:00:00',40,'flowers','varmahalakshmi','allStates','diyas',true,'paayasa','ghujiya',true,true);
INSERT INTO festivalss VALUES(27,'kumbh mela','2022-8-20','tuesday','national festival',5,5,'India','10:00:00',40,'flowers','varmahalakshmi','allStates','diyas',true,'paayasa','ghujiya',true,true);
INSERT INTO festivalss VALUES(28,'christmass','2022-8-20','tuesday','national festival',5,5,'India','10:00:00',40,'flowers','varmahalakshmi','allStates','diyas',true,'paayasa','ghujiya',true,true);
INSERT INTO festivalss VALUES(29,'hanukkah','2022-8-20','tuesday','national festival',5,5,'India','10:00:00',40,'flowers','varmahalakshmi','allStates','diyas',true,'paayasa','ghujiya',true,true);
INSERT INTO festivalss VALUES(30,'easter','2022-8-20','tuesday','national festival',5,5,'India','10:00:00',40,'flowers','varmahalakshmi','allStates','diyas',true,'paayasa','ghujiya',true,true);
INSERT INTO festivalss VALUES(31,'Engineersday','2022-8-20','wednesday','religious festival',5,5,'India','10:00:00',40,'flowers','varmahalakshmi','allStates','diyas',true,'paayasa','ghujiya',true,true);
INSERT INTO festivalss VALUES(32,'bhumi unime','2022-8-20','tuesday','religious festival',5,5,'India','10:00:00',40,'flowers','varmahalakshmi','allStates','diyas',true,'paayasa','ghujiya',true,true);
INSERT INTO festivalss VALUES(33,'coachella','2022-8-20','monday','religious festival',5,5,'India','10:00:00',40,'flowers','varmahalakshmi','allStates','diyas',true,'paayasa','ghujiya',true,true);
INSERT INTO festivalss VALUES(34,'lollapalooza','2022-8-20','sunday','religious festival',5,5,'India','10:00:00',40,'flowers','varmahalakshmi','allStates','diyas',true,'paayasa','ghujiya',true,true);
INSERT INTO festivalss VALUES(35,'mewar','2022-10-28','saturday','religious festival',5,5,'India','10:00:00',40,'flowers','varmahalakshmi','allStates','diyas',true,'paayasa','ghujiya',true,true);
INSERT INTO festivalss VALUES(36,'bihu','2022-9-26','friday','religious festival',5,5,'India','10:00:00',40,'flowers','varmahalakshmi','allStates','diyas',true,'paayasa','ghujiya',true,true);
INSERT INTO festivalss VALUES(37,'vasanthapanchami','2022-8-24','thursday','religious festival',5,5,'India','10:00:00',40,'flowers','varmahalakshmi','allStates','diyas',true,'paayasa','ghujiya',true,true);
INSERT INTO festivalss VALUES(38,'chhatth puja','2022-6-22','wednesday','religious festival',5,5,'India','10:00:00',40,'flowers','chatthpuja','allStates','pooja',true,'rasgulla','frenchfries',true,false);
INSERT INTO festivalss VALUES(39,'fathersday','2022-7-14','tuesday','religious festival',5,5,'India','10:00:00',40,'flowers','father','allStates','fatherslove',true,'rasmali','kachoori',true,true);
INSERT INTO festivalss VALUES(40,'rakshabandhana','2022-4-13','monday','religious festival',5,5,'India','10:00:00',40,'flowers','brother','allStates','raakhi',true,'peda','gobi',true,true);

SELECT COUNT(*) FROM festivalss;
